import type {
  Achievement,
  AdminUser,
  CommunityPost,
  EcoCategory,
  Habit,
} from "@/lib/types";

export const mockUsers: AdminUser[] = [
  {
    id: "user-1",
    username: "akmaral",
    email: "akmaral@ecoiz.app",
    role: "ADMIN",
    isEmailVerified: true,
    ecoPoints: 2480,
    streakDays: 18,
    postsCount: 12,
    createdAt: "2025-02-10",
    status: "ACTIVE",
  },
  {
    id: "user-2",
    username: "nurdana",
    email: "nurdana@ecoiz.app",
    role: "MODERATOR",
    isEmailVerified: true,
    ecoPoints: 1640,
    streakDays: 9,
    postsCount: 7,
    createdAt: "2025-02-19",
    status: "ACTIVE",
  },
  {
    id: "user-3",
    username: "green_step",
    email: "user1@ecoiz.app",
    role: "USER",
    isEmailVerified: false,
    ecoPoints: 820,
    streakDays: 4,
    postsCount: 3,
    createdAt: "2025-03-01",
    status: "REVIEW",
  },
  {
    id: "user-4",
    username: "urban_leaf",
    email: "user2@ecoiz.app",
    role: "USER",
    isEmailVerified: true,
    ecoPoints: 320,
    streakDays: 1,
    postsCount: 1,
    createdAt: "2025-03-12",
    status: "SUSPENDED",
  },
];

export const mockCategories: EcoCategory[] = [
  {
    id: "cat-1",
    name: "transport",
    description: "Sustainable transport",
    color: "orange",
    icon: "transport",
  },
  {
    id: "cat-2",
    name: "water",
    description: "Water conservation",
    color: "blue",
    icon: "water",
  },
  {
    id: "cat-3",
    name: "plastic",
    description: "Plastic reduction",
    color: "teal",
    icon: "plastic",
  },
];

export const mockHabits: Habit[] = [
  {
    id: "habit-1",
    title: "Пешая прогулка",
    category: "transport",
    points: 20,
    co2Value: 1.5,
    waterValue: 0,
    energyValue: 0,
  },
  {
    id: "habit-2",
    title: "Короткий душ",
    category: "water",
    points: 15,
    co2Value: 0,
    waterValue: 25,
    energyValue: 0,
  },
  {
    id: "habit-3",
    title: "Сортировка",
    category: "waste",
    points: 15,
    co2Value: 0,
    waterValue: 0,
    energyValue: 0,
  },
  {
    id: "habit-4",
    title: "Выключил свет",
    category: "electricity",
    points: 10,
    co2Value: 0,
    waterValue: 0,
    energyValue: 2,
  },
];

export const mockAchievements: Achievement[] = [
  {
    id: "achievement-1",
    title: "Эко-новичок",
    description: "Использовать многоразовую бутылку 10 раз",
    icon: "badge_1",
    targetValue: 10,
    rewardPoints: 50,
  },
  {
    id: "achievement-2",
    title: "Друг природы",
    description: "Подписаться на 10 пользователей",
    icon: "badge_follow",
    targetValue: 10,
    rewardPoints: 60,
  },
  {
    id: "achievement-3",
    title: "Спасатель климата",
    description: "Сократить 100 кг CO2",
    icon: "badge_co2",
    targetValue: 100,
    rewardPoints: 150,
  },
  {
    id: "achievement-4",
    title: "Энерго-герой",
    description: "Сэкономить 100 кВт·ч энергии",
    icon: "badge_energy",
    targetValue: 100,
    rewardPoints: 120,
  },
];

export const mockPosts: CommunityPost[] = [
  {
    id: "post-1",
    author: "green_step",
    content: "Started walking to university this week instead of taking a taxi.",
    visibility: "PUBLIC",
    state: "Flagged",
    reportsCount: 3,
    createdAt: "2025-03-14",
  },
  {
    id: "post-2",
    author: "eco_daily",
    content: "Shared a checklist for reducing water use at home.",
    visibility: "FOLLOWERS",
    state: "Published",
    reportsCount: 0,
    createdAt: "2025-03-15",
  },
  {
    id: "post-3",
    author: "urban_leaf",
    content: "Posted a photo dump with repeated promotional captions.",
    visibility: "PUBLIC",
    state: "Needs review",
    reportsCount: 2,
    createdAt: "2025-03-16",
  },
  {
    id: "post-4",
    author: "recycle_hub",
    content: "Community cleanup event recap with location details.",
    visibility: "PUBLIC",
    state: "Hidden",
    reportsCount: 1,
    createdAt: "2025-03-13",
  },
];
